#ifndef __ERROR_CODES_H
#define __ERROR_CODES_H

#define EC_OK (0)
#define EC_INIT_FAILURE (14)

#define EC_UNINIT_FAILURE (70)
#define EC_NETWORKING_UNINIT_FAILURE (71)

#define EC_TCS_CLIENT_INIT_FAILURE (278)
#define EC_TCS_CLIENT_SOCKET_CREATE_FAILURE (279)
#define EC_TCS_CLIENT_CONNECTION_FAILURE (280)
#define EC_TCS_CLIENT_SEND_FAILURE (281)
#define EC_TCS_CLIENT_RECEPTION_FAILURE (283)
#define EC_TCS_CLIENT_SOCKET_SHUTDOWN_FAILURE (284)
#define EC_TCS_CLIENT_SOCKET_CLOSE_FAILURE (285)
#define EC_TCS_CLIENT_SOCKET_FREE_TINYCSOCKET_FAILURE (286)


#endif