#ifndef __ERROR_CODES_H
#define __ERROR_CODES_H

typedef int ErrorCode;

#define EC_OK (0)
#define EC_INIT_FAILURE (14)
#define EC_NETWORKING_INIT_NO_SERVER_NOR_CLIENT_FAILURE (17)
#define EC_INIT_DATABASE_FAILED_TO_ALLOCATE (20)

#define EC_UNINIT_FAILURE (70)
#define EC_NETWORKING_UNINIT_FAILURE (71)

#define EC_CONFIG_BAD_PATH (166)
#define EC_CONFIG_TOML_PARSE_FAILURE (167)
#define EC_CONFIG_SELF_ORIENT_FAILURE (168)
#define EC_CONFIG_NO_FILE_FOUND (169)

#define EC_TCS_CLIENT_INIT_FAILURE (278)
#define EC_TCS_CLIENT_SOCKET_CREATE_FAILURE (279)
#define EC_TCS_CLIENT_CONNECTION_FAILURE (280)
#define EC_TCS_CLIENT_SEND_FAILURE (281)
#define EC_TCS_CLIENT_RECEPTION_FAILURE (283)
#define EC_TCS_CLIENT_SOCKET_SHUTDOWN_FAILURE (284)
#define EC_TCS_CLIENT_SOCKET_CLOSE_FAILURE (285)
#define EC_TCS_CLIENT_SOCKET_FREE_TINYCSOCKET_FAILURE (286)

#define EC_CWD_NO_SEGMENTS (290)

#define EC_TCS_SERVER_INIT_FAILURE (301)

#define EC_TCS_LISTEN_SOCKET_CREATE_FAILURE (350)
#define EC_TCS_LISTEN_SOCKET_LISTEN_FAILURE (351)
#define EC_TCS_LISTEN_SOCKET_CONNCTION_ACCEPTANCE_FAILURE (352)
#define EC_TCS_LISTEN_SOCKET_DESTRUCTION_FAILURE (353)
#define EC_TCS_SERVER_SOCKET_RECEPTION_FAILURE (354)
#define EC_TCS_SERVER_DATA_TRANSMISSION_FAILURE (355)
#define EC_TCS_SERVER_SOCKET_SHUTDOWN_FAILURE (356)
#define EC_TCS_SERVER_SOCKET_DESTRUCTION_FAILURE (357)

#define EC_UNKNOWN_APPLICATION_MODE (672)

#define EC_CHAT_MAX_CHAT_DEPTH_EXCEEDED (701)

#define EC_PASSED_NULL (-5)

#define EC_SERIALIZE_FAILURE_BOCCE_BALL_STATE (170)

#endif